// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// match_nearest
DataFrame match_nearest(NumericVector ps, IntegerVector treat, IntegerVector id, double caliper);
RcppExport SEXP _RcppMatch_match_nearest(SEXP psSEXP, SEXP treatSEXP, SEXP idSEXP, SEXP caliperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ps(psSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type treat(treatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< double >::type caliper(caliperSEXP);
    rcpp_result_gen = Rcpp::wrap(match_nearest(ps, treat, id, caliper));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppMatch_match_nearest", (DL_FUNC) &_RcppMatch_match_nearest, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppMatch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
