# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

match_nearest <- function(ps, treat, id, caliper = -1.0) {
    .Call(`_RcppMatch_match_nearest`, ps, treat, id, caliper)
}

